#!/bin/bash
# Reporting Module - Comprehensive Security Reporting

# Get base directory
BASE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Color codes
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

# Load configuration
source "$BASE_DIR/config/settings.conf"

# Generate security report
generate_security_report() {
    local timestamp
    timestamp=$(date '+%Y%m%d_%H%M%S')
    local report_file="$BASE_DIR/reports/comprehensive_security_report_$timestamp.txt"
    
    echo -e "${BLUE}[REPORT] Generating comprehensive security report${NC}"
    
    # Get latest data
    local latest_discovery
    latest_discovery=$(ls -td "$BASE_DIR/data/discovery_"* 2>/dev/null | head -1)
    local latest_assessment
    latest_assessment=$(ls -td "$BASE_DIR/data/assessment_"* 2>/dev/null | head -1)
    
    if [ -z "$latest_discovery" ] || [ -z "$latest_assessment" ]; then
        echo -e "${RED}[ERROR] Required data not found. Run discovery and assessment first.${NC}"
        echo "Run: ./bin/orgsec-scanner auto"
        return 1
    fi
    
    # Generate text report
    generate_text_report "$report_file" "$latest_discovery" "$latest_assessment"
    
    echo -e "${GREEN}[REPORT] Comprehensive report generated: $report_file${NC}"
}

# Generate text report
generate_text_report() {
    local report_file="$1"
    local discovery_dir="$2"
    local assessment_dir="$3"
    
    local total_devices
    total_devices=$(grep -c "Host is up" "$discovery_dir/host_discovery.nmap" 2>/dev/null || echo "0")
    local critical_issues
    critical_issues=$(find "$assessment_dir" -name "ftp_alert.txt" 2>/dev/null | wc -l)
    local warning_issues
    warning_issues=$(find "$assessment_dir" -name "ssh_weak.txt" 2>/dev/null | wc -l)
    
    {
        echo "COMPREHENSIVE SECURITY ASSESSMENT REPORT"
        echo "========================================"
        echo "Report Date: $(date)"
        echo "Generated by: OrgSecScanner v1.0"
        echo ""
        
        echo "EXECUTIVE SUMMARY"
        echo "----------------"
        echo "Total Devices Scanned: $total_devices"
        echo "Critical Security Issues: $critical_issues"
        echo "Warning Issues: $warning_issues"
        echo "Overall Security Posture: $(get_overall_posture "$critical_issues" "$warning_issues")"
        echo ""
        
        echo "CRITICAL FINDINGS"
        echo "-----------------"
        if [ "$critical_issues" -gt 0 ]; then
            find "$assessment_dir" -name "ftp_alert.txt" 2>/dev/null | while read -r alert; do
                local device
                device=$(dirname "$alert" | xargs basename | tr '_' '.')
                echo "🚨 CRITICAL: FTP service enabled on $device"
            done
        else
            echo "✅ No critical issues found"
        fi
        echo ""
        
        echo "WARNING FINDINGS"
        echo "----------------"
        if [ "$warning_issues" -gt 0 ]; then
            find "$assessment_dir" -name "ssh_weak.txt" 2>/dev/null | while read -r alert; do
                local device
                device=$(dirname "$alert" | xargs basename | tr '_' '.')
                echo "⚠️  WARNING: Weak SSH algorithms on $device"
            done
        else
            echo "✅ No warning issues found"
        fi
        echo ""
        
        echo "DEVICE INVENTORY"
        echo "----------------"
        echo "Network Infrastructure: $(grep -c "^10.10.84.2" "$discovery_dir/hosts.txt" 2>/dev/null || echo "0")"
        echo "Total Servers: $(grep -c "^10.10.84." "$discovery_dir/hosts.txt" 2>/dev/null || echo "0")"
        echo "Workstations: ~$(($total_devices - 5))"  # Rough estimate
        echo ""
        
        echo "SECURITY RECOMMENDATIONS"
        echo "-----------------------"
        echo "IMMEDIATE ACTIONS (24-48 hours):"
        echo "1. Disable FTP services on network devices"
        echo "2. Harden SSH configurations"
        echo "3. Change default credentials on web interfaces"
        echo ""
        echo "SHORT-TERM ACTIONS (1 week):"
        echo "1. Implement network segmentation"
        echo "2. Configure firewall rules"
        echo "3. Set up security monitoring"
        echo ""
        echo "ONGOING ACTIONS:"
        echo "1. Regular vulnerability assessments"
        echo "2. Security patch management"
        echo "3. Employee security training"
        
    } > "$report_file"
}

# Helper function
get_overall_posture() {
    local critical="$1"
    local warnings="$2"
    
    if [ "$critical" -gt 0 ]; then
        echo "AT RISK - Immediate action required"
    elif [ "$warnings" -gt 0 ]; then
        echo "NEEDS IMPROVEMENT - Review recommended"
    else
        echo "SECURE - Good security posture"
    fi
}
